### ISSUE TITLE
Incorrect README: Symbol's function definition is void: nlinum-hl--flush

### ISSUE THREAD

**Issue by ogdenwebb** [hlissner/emacs-nlinum-hl#2]
I'm not sure, but probably you don't export this function. I mean without the following it works fine:
```emacs-lisp
(advice-add #'select-window :before #'nlinum-hl--flush)
(advice-add #'select-window :after  #'nlinum-hl--flush)
```

**Comment by hlissner** [comment]
My bad. I did a major refactor before I released the plugin but forgot to update the README. It is up-to-date as of https://github.com/hlissner/emacs-nlinum-hl/commit/d2df27578fcd7393c13b6ccc34028c0a2cda4ea1.

The correct function is ~`nlinum-hl-flush`~ `nlinum-hl-do-flush`
